# This file was generated by GoReleaser. DO NOT EDIT.
cask "franta" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "3b3986962c57602bac2a09e7ff104a620dcc5f8fb030d49b1a4a2b4efd9cb21e"
      url "https://github.com/jindrichskupa/franta/releases/download/v#{version}/franta_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9ad5b01da39abeeed36ac5ee9c7cc139a68dd131825de1637cf6df8d21065336"
      url "https://github.com/jindrichskupa/franta/releases/download/v#{version}/franta_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3e74dff0facd1a1a62f49cfe651585b9377c24204c263a8ca14b22fe5cfa5d45"
      url "https://github.com/jindrichskupa/franta/releases/download/v#{version}/franta_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "41454e3660726fe42e1f77ed5a4f0a0746516cb08061d83388b66af60607c658"
      url "https://github.com/jindrichskupa/franta/releases/download/v#{version}/franta_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "franta"
  desc "Terminal UI for Apache Kafka with MSK IAM auth, filter DSL, consumer-group lag, and Schema Registry decoding"
  homepage "https://github.com/jindrichskupa/franta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "franta"
  manpage "man/franta.1"
  bash_completion "completions/franta.bash"
  fish_completion "completions/franta.fish"
  zsh_completion "completions/franta.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/franta"]
    end
  end

  # No zap stanza required

end
