# This file was generated by GoReleaser. DO NOT EDIT.
cask "franta" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "a32a1107489e249946e88e055cb447a5b420c6b6135415ce07f720b70364accb"
      url "https://github.com/jindrichskupa/franta/releases/download/v#{version}/franta_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "368a9ce05cb63c33e60a1ad2e371582b9adb4f78f65ea90bf8260a1b4e1e7902"
      url "https://github.com/jindrichskupa/franta/releases/download/v#{version}/franta_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "01addb9a4c28d827d8b8f56d49f9cfe87e9c3ddb64bf84ac41e26536f6559692"
      url "https://github.com/jindrichskupa/franta/releases/download/v#{version}/franta_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "14f378ef2183a4ac52ca586badd3ba7b0472137a0642fc86410a010da505170b"
      url "https://github.com/jindrichskupa/franta/releases/download/v#{version}/franta_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "franta"
  desc "Terminal UI for Apache Kafka with MSK IAM auth, filter DSL, consumer-group lag, and Schema Registry decoding"
  homepage "https://github.com/jindrichskupa/franta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "franta"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/franta"]
    end
  end

  # No zap stanza required

end
