# This file was generated by GoReleaser. DO NOT EDIT.
cask "franta" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "3096b3ca87bf0758df9cc8edeabba80561bde1680eddb7e1d039ac6078184c57"
      url "https://github.com/jindrichskupa/franta/releases/download/v#{version}/franta_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4de00d07309cbd2fc2229cc4c6caeba9c7f67ffe478a920aa82b5f4c69e100ba"
      url "https://github.com/jindrichskupa/franta/releases/download/v#{version}/franta_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d7cbfdaa8e8df580625f1fbd2fd435cbec53877e564d4ad2897d987c3f775858"
      url "https://github.com/jindrichskupa/franta/releases/download/v#{version}/franta_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4eeac22eed9750c814cd089f974c96fa9ecbca3184583b94818d435f4a259f0a"
      url "https://github.com/jindrichskupa/franta/releases/download/v#{version}/franta_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "franta"
  desc "Terminal UI for Apache Kafka with MSK IAM auth, filter DSL, consumer-group lag, and Schema Registry decoding"
  homepage "https://github.com/jindrichskupa/franta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "franta"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/franta"]
    end
  end

  # No zap stanza required

end
